### ISSUE TITLE
Revert No passcode after respring

### ISSUE THREAD

**Issue by insert-usernamehere** [haxi0/Jaility#1]
Hello, I’ve been using this and it’s been working perfectly, however I am curious about how I would go about reenabling the password prompt after respiring. Thanks in advance for you help!

**Comment by insert-usernamehere** [comment]
Oh well I figured it out, so now this is a feature request to add a button to do it from the app

**Comment by haxi0** [comment]
As was said in the .README file:
If you used disable lock after respring, and want to enable it back, you need to go to /var/Managed Preferences/mobile and edit the key in com.apple.springboard.plist named SBDontLockAfterCrash to false.
