### ISSUE TITLE
Can't see com.apple.springboard.plist

### ISSUE THREAD

**Issue by areltiyan** [haxi0/Jaility#4]
Hi, i cant see file com.apple.springboard.plist
i want to enable passcode after respring

![2134DCD8-3853-47AE-A5D5-48F3A4455591](https://user-images.githubusercontent.com/54056041/196017428-4064ea04-a043-4907-b7c8-3ad0fc3140f9.png)

**Comment by haxi0** [comment]
did you already disable it? you can also try enable the lock after respring button. it was added in 2.1

**Comment by areltiyan** [comment]
> did you already disable it? you can also try enable the lock after respring button. it was added in 2.1

already click on app but not working
on iPhone 13 Pro 15.5 Beta 4

**Comment by haxi0** [comment]
try Santander or either FilzaTS by nebula

**Comment by haxi0** [comment]
closed due to the inactivity
