### ISSUE TITLE
Crashing Themes downloading + optimizing for iPadOS 

### ISSUE THREAD

**Issue by ChrisGleich1AufsMaul** [haxi0/Jaility#5]
1. As others already reported, it keeps crashing when you try to download themes
2. It would be very nice, if you could optimize the app for iPadOS and maybe use the landscape mode

![3EBABD49-6D69-4B57-A0BF-4F979DDDFB37](https://user-images.githubusercontent.com/49039734/196023130-6a21d9f5-1b70-4742-86cb-ddd9c0ecfec8.png)

**Comment by haxi0** [comment]
try 2.1.1, will soon optimize it.

**Comment by ChrisGleich1AufsMaul** [comment]
> try 2.1.1, will soon optimize it.

Wow, you are quickly
Thank you, I'll try 👌
